# Configuration for keyboard layout analysis pipeline

# Data settings
data:
  input_file: "data/output_all4studies_406participants/tables/filtered_bigram_data.csv"
  #input_file: "data/output_all4studies_406participants/tables/filtered_consistent_choices.csv"
  #input_file: "data/output_all4studies_303of406participants_0improbable/tables/filtered_bigram_data.csv"
  #input_file: "data/output_all4studies_303of406participants_0improbable/tables/filtered_consistent_choices.csv"

# Keyboard layout settings
layout:
  left_chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

# Feature settings
features:
  design:
    - 'row_sum'
    - 'engram_sum'
  control:
    - 'freq'
  add_interactions: false
  interaction_pairs: []

# Output directory structure
output:
  base_dir: "output"
  logs: "output/logs"
  
  # Model outputs
  model:
    dir: "output/model"
    results: "output/model/glmm_results"
    visualizations:
      mcmc: "output/model/visualizations/mcmc"
      vi: "output/model/visualizations/vi"
  
  # Feature space outputs
  feature_space:
    dir: "output/feature_space"
    visualizations: "output/feature_space/visualizations"
    analysis: "output/feature_space/analysis"
    recommendations: "output/feature_space/recommendations.txt"
    pca_plot: "output/feature_space/visualizations/pca_projection.png"
    bigram_graph: "output/feature_space/visualizations/bigram_graph.png"
  
  # Timing frequency analysis outputs
  timing_frequency:
    dir: "output/timing_frequency"
    visualizations: "output/timing_frequency/visualizations"
    analysis: "output/timing_frequency/analysis"
    relationship_plot: "output/timing_frequency/visualizations/relationship.png"
    groups_plot: "output/timing_frequency/visualizations/groups"
  
  # Comfort scores
  comfort_scores: "output/scores/bigram_comfort_scores.csv"

# Analysis settings
analysis:
  feature_space:
    enabled: true
    check_multicollinearity: true
    recommend_bigrams: true
    num_recommendations: 30
  
  timing_frequency:
    enabled: true
    n_groups: 4

# Model settings
model:
  train: true
  #inference_method: 'mcmc'
  inference_method: 'variational'
  num_samples: 10  #2000
  chains: 2  #8

# Scoring settings
scoring:
  enabled: true
  mirror_scores: true

# Visualization settings
visualization:
  enabled: true

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "output/logs/pipeline.log"
