#===========#
# SETTINGS  #
#===========#
# Data settings
data:
  file: "data/input/output_all4studies_406participants/tables/filtered_bigram_data.csv"
  # file: "data/input/output_all4studies_406participants/tables/filtered_consistent_choices.csv"
  # file: "data/input/output_all4studies_303of406participants_0improbable/tables/filtered_bigram_data.csv"
  # file: "data/input/output_all4studies_303of406participants_0improbable/tables/filtered_consistent_choices.csv"

  # Participant splits
  splits:
    generate: true
    train_ratio: 0.8
  
  # Keyboard layout
  layout:
    left_chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

# Analysis settings
analysis:
  # Feature evaluation
  feature_evaluation:
    enabled: true
    n_splits: 5
    n_samples: 1000
    test_size: 0.2
    combinations:
      - ['same_finger', 'adjacent_finger', 'adj_finger_diff_row', 'adj_finger_skip',
         'rows_apart', 'skip_home', 'columns_apart', 'angle_apart',
         'outward_roll', 'outward_roll_same_row', 'outward_skip',
         'middle_column', 'sum_engram_position_values', 'sum_row_position_values',
         'sum_finger_values', 'finger1or4_top_above', 'finger2or3_bottom_below', 'finger_pairs']
      - ['same_finger', 'adj_finger_skip', 'skip_home', 'angle_apart', 'outward_roll_same_row',
         'middle_column', 'sum_engram_position_values', 'sum_row_position_values',
         'sum_finger_values', 'finger1or4_top_above', 'finger2or3_bottom_below']

  # Feature space analysis
  feature_space:
    enabled: true
    check_multicollinearity: true
    recommend_bigrams: true
    num_recommendations: 30

  # Frequency/timing analysis
  frequency_timing:
    enabled: true
    n_groups: 4

  # Model settings
  model:
    train: true
    inference_method: 'variational' #'mcmc'  # or 'variational'
    num_samples: 100 #2000
    chains: 4 #8
    evaluate_test: true
    scoring:
      enabled: true
      mirror_left_right_scores: true
    visualization:
      enabled: true

# Feature definitions
features:
  # Feature interactions
  interactions:
    enabled: true
    pairs:
      - ['adjacent_finger', 'skip_home']

  # Feature groups
  groups:
    design:
      - 'same_finger'
      - 'adjacent_finger'
      - 'adj_finger_diff_row'
      - 'adj_finger_skip'
      - 'rows_apart'
      - 'skip_home'
      - 'columns_apart'
      - 'angle_apart'
      - 'outward_roll'
      - 'outward_roll_same_row'
      - 'outward_skip'
      - 'middle_column'
      - 'sum_engram_position_values'
      - 'sum_row_position_values'
      - 'sum_finger_values'
      - 'finger1or4_top_above'
      - 'finger2or3_bottom_below'
      - 'finger_pairs'
    control:
      - 'qwerty_bigram_frequency'
      - 'typing_time'

  # All available features
  all_features:
    - 'qwerty_bigram_frequency'
    - 'typing_time'
    - 'same_finger'
    - 'adjacent_finger'
    - 'adj_finger_diff_row'
    - 'adj_finger_skip'
    - 'rows_apart'
    - 'skip_home'
    - 'columns_apart'
    - 'angle_apart'
    - 'outward_roll'
    - 'outward_roll_same_row'
    - 'outward_skip'
    - 'middle_column'
    - 'sum_engram_position_values'
    - 'sum_row_position_values'
    - 'sum_finger_values'
    - 'finger1or4_top_above'
    - 'finger2or3_bottom_below'
    - 'finger_pairs'

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

#========#
# PATHS  #
#========#
paths:
  # Base directories
  base: "output"
  logs: "output/logs/pipeline.log"
  splits: "data/splits/train_test_indices.npz"

  # Analysis outputs
  feature_evaluation: "output/feature_evaluation"
  
  feature_space:
    dir: "output/feature_space"
    analysis: "output/feature_space/analysis.txt"
    recommendations: "output/feature_space/recommendations.txt"
    pca: "output/feature_space/pca.png"
    bigram_graph: "output/feature_space/bigram_graph.png"
    underrepresented: "output/feature_space/underrepresented.png"
  
  frequency_timing:
    dir: "output/frequency_timing"
    analysis: "output/frequency_timing/analysis.txt"
    relationship: "output/frequency_timing/relationship.png"
    group_directory: "output/frequency_timing/groups"
  
  model:
    dir: "output/model"
    results: "output/model/results"
    diagnostics: "output/model/diagnostics_{inference_method}.png"
    forest: "output/model/forest_{inference_method}.png"
    posterior: "output/model/posterior_{inference_method}.png"
    participant_effects: "output/model/participant_effects_{inference_method}.png"
    sensitivity: "output/model/sensitivity_{inference_method}.png"
  
  scores: "output/scores/bigram_comfort_scores.csv"
