#===========#
# SETTINGS  #
#===========#
# Data settings
data:
  file: "data/input/output_all4studies_406participants/tables/filtered_bigram_data.csv"
  # file: "data/input/output_all4studies_406participants/tables/filtered_consistent_choices.csv"
  # file: "data/input/output_all4studies_303of406participants_0improbable/tables/filtered_bigram_data.csv"
  # file: "data/input/output_all4studies_303of406participants_0improbable/tables/filtered_consistent_choices.csv"

  # Participant splits
  splits:
    generate: false # One time per file (output_all4studies_406participants/ on 2024-11-25)
    train_ratio: 0.8
  
  # Keyboard layout
  layout:
    left_chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

# Analysis settings
analysis:

  # Frequency/timing analysis
  frequency_timing:
    enabled: true
    n_groups: 4

  # Feature space analysis
  feature_space:
    enabled: true
    check_multicollinearity: true
    recommend_bigrams: true
    num_recommendations: 30

  # Feature evaluation
  feature_evaluation:
    enabled: true
    n_splits: 5
    n_samples: 10000
    chains: 8
    target_accept: 0.85
    combinations:
      - name: "base9features"
        features: ['same_finger', 'sum_finger_values', 'adj_finger_diff_row', 
                   'rows_apart', 'angle_apart', 'outward_roll', 
                   'middle_column', 'sum_engram_position_values', 'sum_row_position_values']
        interactions: "data/filtered_feature_interactions.txt"

# Model settings
model:
  train: false
  inference_method: 'mcmc'
  n_samples: 10000
  chains: 8
  target_accept: 0.85
  evaluate_test: true
  scoring:
    enabled: true
    mirror_left_right_scores: true
  visualization:
    enabled: true

  # Feature definitions
  features:
    interactions:
      enabled: true
      interactions:
        - ['same_finger', 'sum_finger_values']
        - ['same_finger', 'sum_finger_values', 'rows_apart']
        - ['same_finger', 'sum_finger_values', 'rows_apart', 'sum_row_position_values']

    # Feature groups
    groups:
      design:
        - 'same_finger'

      control:
        - 'qwerty_bigram_frequency'
        - 'typing_time'

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

#========#
# PATHS  #
#========#
paths:
  # Base directories
  base: "output"
  logs: "output/logs/pipeline.log"
  splits: "data/splits/train_test_indices.npz"

  # Analysis outputs
  feature_evaluation: "output/feature_evaluation"
  
  feature_space:
    dir: "output/feature_space"
    analysis: "output/feature_space/analysis.txt"
    pca: "output/feature_space/pca.png"
    bigram_graph: "output/feature_space/bigram_graph.png"
    underrepresented: "output/feature_space/underrepresented.png"
  
  frequency_timing:
    dir: "output/frequency_timing"
    analysis: "output/frequency_timing/analysis.txt"
    relationship: "output/frequency_timing/relationship.png"
    group_directory: "output/frequency_timing"
  
  model:
    dir: "output/model"
    results: "output/model/results"
    diagnostics: "output/model/diagnostics_{inference_method}.png"
    forest: "output/model/forest_{inference_method}.png"
    posterior: "output/model/posterior_{inference_method}.png"
    participant_effects: "output/model/participant_effects_{inference_method}.png"
    sensitivity: "output/model/sensitivity_{inference_method}.png"
  
  scores: "output/scores/bigram_comfort_scores.csv"
