# Configuration for keyboard layout analysis pipeline

# Data settings
data:
  input_file: "data/input/output_all4studies_406participants/tables/filtered_bigram_data.csv"
  #input_file: "data/input/output_all4studies_406participants/tables/filtered_consistent_choices.csv"
  #input_file: "data/oinput/utput_all4studies_303of406participants_0improbable/tables/filtered_bigram_data.csv"
  #input_file: "data/input/output_all4studies_303of406participants_0improbable/tables/filtered_consistent_choices.csv"
  splits_file: "data/splits/train_test_indices.npz"  # New entry

# Keyboard layout settings
layout:
  left_chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

# Feature settings
features:
  design:
    - 'row_sum'
    - 'engram_sum'
  control:
    - 'freq'
  add_interactions: false
  interaction_pairs: []

# Feature evaluation settings
feature_evaluation:
  enabled: true
  dir: "output/feature_evaluation"
  analysis_dir: "output/feature_evaluation/analysis"
  plots_dir: "output/feature_evaluation/plots"
  n_splits: 5
  n_samples: 1000
  candidate_features:
    - ['row_sum', 'engram_sum']
    - ['row_sum', 'engram_sum', 'freq']
    - ['row_sum']
    - ['engram_sum']
  test_size: 0.2  # For train/test split

# Output directory structure
output:
  base_dir: "output"
  logs: "output/logs"
  
  # Model outputs
  model:
    dir: "output/model"
    results: "output/model/results"
    diagnostics: "output/model/diagnostics_{inference_method}.png"
    forest: "output/model/forest_{inference_method}.png"
    posterior: "output/model/posterior_{inference_method}.png"
    participant_effects: "output/model/participant_effects_{inference_method}.png"
  
  # Feature space analysis
  feature_space:
    enabled: true
    check_multicollinearity: true
    recommend_bigrams: true
    num_recommendations: 30
    dir: "output/feature_space"
    analysis: "output/feature_space/analysis.txt"
    recommendations: "output/feature_space/recommendations.txt"
    pca: "output/feature_space/pca.png"
    bigram_graph: "output/feature_space/bigram_graph.png"
    underrepresented: "output/feature_space/underrepresented.png"
  
  # Timing frequency analysis
  timing_frequency:
    enabled: true
    n_groups: 4
    dir: "output/timing_frequency"
    analysis: "output/timing_frequency/analysis.txt"
    relationship: "output/timing_frequency/relationship.png"
    groups: "output/timing_frequency/groups"
  
  # Comfort scores
  comfort_scores: "output/scores/bigram_comfort_scores.csv"

# Model settings
model:
  train: true
  inference_method: 'variational'  # or 'mcmc'
  num_samples: 20  #2000
  chains: 2  #8

# Scoring settings
scoring:
  enabled: true
  mirror_scores: true

# Visualization settings
visualization:
  enabled: true

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "output/logs/pipeline.log"