# Data settings
data:
  #input_file: "data/input/processed_output_all4studies_303of406participants_0inconsistencies_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #input_file: "data/input/processed_output_all4studies_303of406participants_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #input_file: "data/input/processed_output_all4studies_406participants_0inconsistencies/tables/processed_data/processed_bigram_data.csv"
  input_file: "data/input/processed_output_all4studies_406participants/tables/processed_data/processed_bigram_data.csv"
  output_dir: "output"

  splits:
    test_ratio: 0.2
    random_seed: 42
    split_data_file: "data/split_train_test_indices.npz"
  
  # Keyboard layout
  layout:
    chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

  visualization:
    output_dir: "output/plots"
    save_plots: true
    dpi: 300

# Feature settings
features:
  base_features:
    - typing_time
    - same_finger
    - sum_finger_values
    - adj_finger_diff_row
    - rows_apart
    - angle_apart
    - outward_roll
    - middle_column
    - sum_engram_position_values
    - sum_row_position_values
  interactions_file: "data/feature_interactions.txt"

# Feature evaluation settings
feature_evaluation:
  thresholds:
    importance: 0.05  # Threshold for feature selection
    stability: 0.7    # Minimum stability requirement
  importance_weights:
    model_effect: 0.4
    correlation: 0.3
    mutual_info: 0.3
  metrics_file: "output/feature_metrics.csv"

feature_selection:
  n_iterations: 1
  importance_threshold: 0.1
  interaction_threshold: 0.15
  metric_weights:
    inclusion_probability: 0.3
    effect_magnitude: 0.3
    effect_consistency: 0.2
    predictive_impact: 0.2
    correlation: 0.2
    mutual_information: 0.2
    model_effect: 0.4
    stability: 0.2

recommendations:
  # Scoring weights for different components
  weights:  # sum to 1
    prediction_uncertainty: 0.25
    comfort_uncertainty: 0.15
    feature_space: 0.15
    correlation: 0.075
    mutual_information: 0.075
    stability: 0.1
    interaction_testing: 0.1
    transitivity: 0.1
  # Output settings
  n_recommendations: 20
  max_candidates: 1000
  recommendations_file: "output/recommended_bigram_pairs.csv"
  save_plots: true

model:
  chains: 1        # number of parallel chains
  warmup: 10     # warmup/adaptation samples per chain
  samples: 10    # post-warmup samples per chain
  feature_scale: 2.0    # prior scale for feature weights
  participant_scale: 1.0 # prior scale for participant effects

# Logging settings
logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  output_file: "output/debug.log"
  console_level: "INFO"
  file_level: "DEBUG"
