# Configuration for keyboard layout analysis pipeline

# Data settings
data:
  input_file: "data/input/output_all4studies_406participants/tables/filtered_bigram_data.csv"
  #input_file: "data/input/output_all4studies_406participants/tables/filtered_consistent_choices.csv"
  #input_file: "data/oinput/utput_all4studies_303of406participants_0improbable/tables/filtered_bigram_data.csv"
  #input_file: "data/input/output_all4studies_303of406participants_0improbable/tables/filtered_consistent_choices.csv"
  splits_file: "data/splits/train_test_indices.npz"  # New entry

# Keyboard layout settings
layout:
  left_chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

# Feature settings
features:
  # Define features
  all_features:
    - name: 'freq'
      type: 'frequency'
      description: 'Bigram frequency'
  
    - name: 'engram_sum'
      type: 'position'
      description: 'Sum of engram position values'
      
    - name: 'row_sum'
      type: 'position'
      description: 'Sum of row position values'
  
  # Group features by their role
  groups:
    design:
      - 'row_sum'
      - 'engram_sum'
    control:
      - 'freq'
  
  # Feature interactions to consider
  interactions:
    enabled: false
    pairs:
      - ['row_sum', 'engram_sum']

# Output directory structure
output:
  base_dir: "output"
  logs: "output/logs"
  
  # Feature evaluation outputs
  feature_evaluation:
    dir: "output/feature_evaluation"
  
  # Model outputs
  model:
    dir: "output/model"
    results: "output/model/results"
    diagnostics: "output/model/diagnostics_{inference_method}.png"
    forest: "output/model/forest_{inference_method}.png"
    posterior: "output/model/posterior_{inference_method}.png"
    participant_effects: "output/model/participant_effects_{inference_method}.png"
  
  # Feature space analysis
  feature_space:
    enabled: true
    check_multicollinearity: true
    recommend_bigrams: true
    num_recommendations: 30
    dir: "output/feature_space"
    analysis: "output/feature_space/analysis.txt"
    recommendations: "output/feature_space/recommendations.txt"
    pca: "output/feature_space/pca.png"
    bigram_graph: "output/feature_space/bigram_graph.png"
    underrepresented: "output/feature_space/underrepresented.png"
  
  # Timing frequency analysis
  frequency_timing:
      enabled: true
      n_groups: 4
      dir: "output/frequency_timing"
      analysis: "output/frequency_timing/analysis.txt"
      relationship: "output/frequency_timing/relationship.png"
      group_directory: "output/frequency_timing/groups" 
  
  # Comfort scores
  scores: "output/scores/bigram_comfort_scores.csv"

# Feature evaluation settings
feature_evaluation:
  enabled: true
  n_splits: 5
  n_samples: 1000
  # List of feature combinations to evaluate
  combinations:
    - ['row_sum', 'engram_sum']
    - ['row_sum', 'engram_sum', 'freq']
    - ['row_sum']
    - ['engram_sum']
  test_size: 0.2

# Model settings
model:
  train: false
  inference_method: 'variational'  # or 'mcmc'
  num_samples: 100  #2000
  chains: 2  #8

# Scoring settings
scoring:
  enabled: false
  mirror_scores: true

# Visualization settings
visualization:
  enabled: true

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "output/logs/pipeline.log"