# Data settings
data:
  #input_file: "data/input/processed_output_all4studies_303of406participants_0inconsistencies_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #input_file: "data/input/processed_output_all4studies_303of406participants_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #input_file: "data/input/processed_output_all4studies_406participants_0inconsistencies/tables/processed_data/processed_bigram_data.csv"
  input_file: "data/input/processed_output_all4studies_406participants/tables/processed_data/processed_bigram_data.csv"
  output_dir: "output"

  splits:
    test_ratio: 0.2
    random_seed: 42
    split_data_file: "data/split_train_test_indices.npz"
  
  # Keyboard layout
  layout:
    chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

  visualization:
    output_dir: "output/plots"
    save_plots: true

# Feature settings
features:
  base_features:
    - typing_time
    - same_finger
    - sum_finger_values
    - adj_finger_diff_row
    - rows_apart
    - angle_apart
    - outward_roll
    - middle_column
    - sum_engram_position_values
    - sum_row_position_values
  interactions_file: "data/feature_interactions.txt"

# Feature evaluation settings
feature_evaluation:
  thresholds:
    importance: 0.05  # Threshold for feature selection
    stability: 0.7    # Minimum stability requirement
  importance_weights:
    model_effect: 0.4
    correlation: 0.3
    mutual_info: 0.3
  metrics_file: "output/feature_metrics.csv"

recommendations:
  n_recommendations: 20  # Number of pairs to recommend
  max_candidates: 1000  # Maximum number of candidate pairs to consider
  weights:
    uncertainty: 0.4
    interaction: 0.3
    transitivity: 0.3
  recommendations_file: "output/recommended_bigram_pairs.csv"

model:
  chains: 8
  target_accept: 0.85
  n_samples: 10000
  cross_validation:
    n_splits: 5
    n_repetitions: 1

# Logging settings
logging:
  # set level to "DEBUG" or "INFO" at the top of main.py
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  output_file: "output/debug.log"
