# engram3/config.yaml
# Configuration file for the keyboard preference learning system.
#
# Controls settings for:
#   - Data input/output paths and processing
#   - Model hyperparameters and training settings
#   - Feature extraction and selection parameters
#   - Recommendation system configuration
#   - Logging and visualization preferences
#
# File Structure:
#   - data: Data handling configuration
#   - features: Feature selection settings
#   - model: Bayesian model parameters
#   - logging: System logging configuration
#   - recommendations: Bigram recommendation settings

# Data settings
data:
  #input_file: "data/input/processed_output_all4studies_303of406participants_0inconsistencies_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #input_file: "data/input/processed_output_all4studies_303of406participants_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #input_file: "data/input/processed_output_all4studies_406participants_0inconsistencies/tables/processed_data/processed_bigram_data.csv"
  input_file: "data/input/processed_output_all4studies_406participants/tables/processed_data/processed_bigram_data.csv"
  output_dir: "output"

  splits:
    test_ratio: 0.2
    random_seed: 42
    split_data_file: "data/split_train_test_indices.npz"
  
  # Keyboard layout
  layout:
    chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

  visualization:
    output_dir: "output/plots"
    dpi: 300

# Feature settings
features:
  base_features:
    - typing_time
    - same_finger
    - sum_finger_values
    - adj_finger_diff_row
    - rows_apart
    - angle_apart
    - outward_roll
    - middle_column
    - sum_engram_position_values
    - sum_row_position_values
  interactions_file: "data/feature_interactions.txt"

# Feature evaluation/selection settings
feature_selection:
  n_iterations: 1
  thresholds:
    importance: 0.1  # Single consolidated threshold
    stability: 0.7
  multiple_testing:
    method: "fdr"  # or "bonferroni"
    alpha: 0.05
  interaction_testing:
    method: "likelihood_ratio"
    minimum_effect_size: 0.1
    hierarchical: true
  metric_weights:  # sum = 1
    model_effect: 0.25
    correlation: 0.15
    mutual_information: 0.15
    inclusion_probability: 0.15
    effect_magnitude: 0.1
    effect_consistency: 0.1
    predictive_impact: 0.1
  metrics_file: "output/feature_metrics.csv"

recommendations:
  # Scoring weights for different components
  weights:  # sum to 1
    prediction_uncertainty: 0.25
    comfort_uncertainty: 0.15
    feature_space: 0.15
    correlation: 0.075
    mutual_information: 0.075
    stability: 0.1
    interaction_testing: 0.1
    transitivity: 0.1
  # Output settings
  n_recommendations: 20
  max_candidates: 1000
  recommendations_file: "output/recommended_bigram_pairs.csv"

model:
  chains: 1        # number of parallel chains
  warmup: 10     # warmup/adaptation samples per chain
  samples: 10    # post-warmup samples per chain
  adapt_delta: 0.7 #0.95     # - helps with divergent transitions
  max_treedepth: 3 #12     # - helps with convergence
  feature_scale: 2.0    # prior scale for feature weights
  participant_scale: 1.0 # prior scale for participant effects

# Logging settings
logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  output_file: "output/debug.log"
  console_level: "INFO"
  file_level: "DEBUG"
