# Data settings
data:
  #file: "data/input/processed_output_all4studies_303of406participants_0inconsistencies_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #file: "data/input/processed_output_all4studies_303of406participants_with_no_improbable/tables/processed_data/processed_bigram_data.csv"
  #file: "data/input/processed_output_all4studies_406participants_0inconsistencies/tables/processed_data/processed_bigram_data.csv"
  file: "data/input/processed_output_all4studies_406participants/tables/processed_data/processed_bigram_data.csv"
  splits:
    test_ratio: 0.2
    random_seed: 42

# Analysis settings
analysis:
  check_transitivity: true
  analyze_features: true
  find_sparse_regions: true
  feature_importance: true

# Logging settings
logging:
  level: "DEBUG"  # Changed from INFO to DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "output/logs/pipeline.log"

# Output paths
paths:
  base: "output"
  analysis: "output/analysis"