# Configuration for keyboard layout analysis pipeline

# Data settings
data:
  input_file: "data/output_all4studies_406participants/tables/filtered_bigram_data.csv"
  #input_file: "data/output_all4studies_406participants/tables/filtered_consistent_choices.csv"
  #input_file: "data/output_all4studies_303of406participants_0improbable/tables/filtered_bigram_data.csv"
  #input_file: "data/output_all4studies_303of406participants_0improbable/tables/filtered_consistent_choices.csv"

# Keyboard layout settings
layout:
  left_chars: ['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']

# Feature settings
features:
  design:
    - 'row_sum'
    - 'engram_sum'
  control:
    - 'freq'
  add_interactions: false
  interaction_pairs: []

# Output directory structure
output:
  base_dir: "output"
  logs: "output/logs"
  
  # Model outputs
  model:
    dir: "output/model"
    results: "output/model/results"
    visualizations:
      dir: "output/model/visualizations"
      mcmc: "output/model/visualizations/mcmc"
      vi: "output/model/visualizations/vi"
  
  # Feature space analysis
  feature_space:
    enabled: true
    check_multicollinearity: true
    recommend_bigrams: true
    num_recommendations: 30
    dir: "output/feature_space"
    files:
      analysis: "output/feature_space/analysis.txt"
      recommendations: "output/feature_space/recommendations.txt"
      vif: "output/feature_space/vif.txt"
      correlations: "output/feature_space/correlations.txt"
    visualizations:
      pca: "output/feature_space/visualizations/pca_projection.png"
      bigram_graph: "output/feature_space/visualizations/bigram_graph.png"
      underrepresented: "output/feature_space/visualizations/underrepresented_areas.png"
  
  # Timing frequency analysis
  timing_frequency:
    enabled: true
    n_groups: 4
    dir: "output/timing_frequency"
    files:
      analysis: "output/timing_frequency/analysis.txt"
    visualizations:
      relationship: "output/timing_frequency/visualizations/relationship.png"
      groups: "output/timing_frequency/visualizations/groups"
  
  # Comfort scores
  comfort_scores: "output/scores/bigram_comfort_scores.csv"

# Model settings
model:
  train: true
  inference_method: 'variational'  # or 'mcmc'
  num_samples: 20  #2000
  chains: 2  #8

# Scoring settings
scoring:
  enabled: true
  mirror_scores: true

# Visualization settings
visualization:
  enabled: true

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "output/logs/pipeline.log"