[tool.poetry]
name = "engram3"
version = "0.1.0"
description = ""
authors = ["Arno Klein <binarybottle@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^2.2.3"
scikit-learn = "^1.5.2"
matplotlib = "^3.9.2"
statsmodels = "^0.14.4"
choix = "^0.3.5"
networkx = "^3.4"
numpy = "^1.24"
pymc = "^5.17.0"
tqdm = "^4.66.5"

[tool.poetry.group.dev.dependencies]
scipy = "^1.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
package-mode = false
